--- #YAML:1.0
name:                Geo-Converter-dms2dd
version:             0.01
abstract:            Parse and convert values in Degrees/Minutes/Seconds formats to decimal degrees
license:             ~
author:              
    - Shawn Laffan <shawnlaffan@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    English:                       0
    Readonly:                      0
    Regexp::Common:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
